### PR TITLE
Making Storage As defined in BoardConfig.mk

### PR DESCRIPTION
**Pull request by diparthshah**
note : u have to also make changes in mkbootimg args. 

Unpack ur stock recovery using Carliv Image kitchen and there u will find all arguments detail.

### CODE REVIEW

**Comment by rishabhrao** [comment]
Thanks
Will change args. 2morrow

**Comment by rishabhrao** [comment]
@diparthshah Done Bro. Added Args. Thanks for the Help.

**Comment by diparthshah** [comment]
Seems to be u didn't changed any values in 
Board_mkbootimgmk_args

**Comment by rishabhrao** [comment]
@diparthshah No Actually there was no need.
I used ur twrp sources.
And seems that my args and urs r the same only.
See my recovery.img-infos containing the kernel and ramdisk offsets.
It also has the args.
[recovery.img-infos.txt](https://github.com/rishabhrao/TWRP_Lava_irisFuel50/files/246774/recovery.img-infos.txt)

**Comment by rishabhrao** [comment]
@diparthshah Actually i know that we should change these and i change them also everytime.
But maybe this time my excitement of getting cm13.0 took me away. I forgot it.
:D :P

**Comment by diparthshah** [comment]
No need to change , most MTK have same value :)

**Comment by rishabhrao** [comment]
Yes.
We use genuine mtk.
:)

**Pull request merged**
